### ISSUE TITLE
Use 100% CPU all the time 

### ISSUE THREAD

**Issue by mdoerfler** [pschichtel/ConvertedSync#13]
Make the converter use as many resources as possible (all them threads!). It would be even more advanced to be able to define a value X and afterwards the converter tries to reach exactly this value. 

By doing so, everybody could:
- Convert files a bit faster
- Heat up the room when the heater is broken in winter
- Create a personal sauna in summer

**Comment by pschichtel** [comment]
As long as the output device is fast enough, the songs are reasonably long and all hardware threads are used (default), the CPU should be running at/near 100%. If the output device is to slow to keep up, more threads are unlikely to help as they would create even more parallel writes.

So there is nothing we can do to increase the CPU utilization when the limiting factor is the output device. However we could warn about low CPU utilization and suggest heating repair services or nearby saunas depending on local weather conditions. WDYT?

**Comment by mdoerfler** [comment]
Sorry for not replying for such a long time. It took me a couple of days to integrate over 9999 CPUs below the floor instead of my old floor heating, sell my old floow heating and buy a nice sauna with another >9999 CPUs inside. That was possible by buying old CPUs. They are cheap, slow and I hope they do create a lot of not unwanted heat.

So my further thoughts on this would be:
- Integrate a feature that converts all songs multiple times in case the writing speed is too low (I have an old HDD here, SDDa are not generating enough heat, what a waste of energy!).
-- Here it would be important to save only one conversion output in order to not allocate too much memory on the disk or using it too often when overwriting the song again and again 
-- In later releases we could think about not saving the converted songs at all to not use the disks that often (would save money and the environment again)
- Warn about low CPU utilization like in your proposal and add a question whether the feature described above should be turned on 
- In case the job is too boring for the CPU, we could also think about an artificial intelligence songwriter to create songs that can afterwards be converted
